use convee_chatbot
go

CREATE SCHEMA USERS
GO
CREATE SCHEMA COMMUNICATION
GO

CREATE TABLE USERS.ADMIN
(
	ADMIN_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NAME VARCHAR(100),
	SURNAME VARCHAR(100),
	DATE_OF_BIRTH DATE,
	DATE_CREATED DATETIME
)

CREATE TABLE USERS.CUSTOMER
(
	CUST_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NAME VARCHAR(100),
	SURNAME VARCHAR(100),
	DATE_OF_BIRTH DATE,
	DATE_CREATED DATETIME
)
CREATE TABLE COMMUNICATION.CHAT
(
	CHAT_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CUST_ID INT NOT NULL,
	FOREIGN KEY (CUST_ID) REFERENCES USERS.CUSTOMER(CUST_ID),
	START_TIMESTAMP DATETIME
)

CREATE TABLE COMMUNICATION.MESSAGE
(
	MESSAGE_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CHAT_ID INT NOT NULL,
	FOREIGN KEY (CHAT_ID) REFERENCES COMMUNICATION.CHAT(CHAT_ID),
	MESSAGE_TEXT VARCHAR(MAX),
	TIMESTAMP DATETIME
)

CREATE TABLE COMMUNICATION.RESPONSE
(
	RESPONSE_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	RESPONSE_TEXT VARCHAR(MAX),
	RESP_TO_MESSAGE_ID INT NOT NULL,
	FOREIGN KEY (RESP_TO_MESSAGE_ID) REFERENCES COMMUNICATION.MESSAGE(MESSAGE_ID),
	TIMESTAMP DATETIME
)

insert into admin values('Mila', 'Mbopha', '12-10-2023','')